server:
    port: 9090

spring:
    datasource:
        url: jdbc:mysql://localhost/servicerep
        name: com.mysql.jdbc.Driver
        username: housemaid
        password: housemaid


logging:
        config: classpath:config/logback-spring.xml